// colonyActions

export const CREATE_COLONY = 'CREATE_COLONY'
export const CREATE_COLONY_ERROR = 'CREATE_COLONY_ERROR'
export const CREATE_COLONY_SUCCESS = 'CREATE_COLONY_SUCCESS'

export const GET_COLONY_CLIENT = 'GET_COLONY_CLIENT'
export const GET_COLONY_CLIENT_ERROR = 'GET_COLONY_CLIENT_ERROR'
export const GET_COLONY_CLIENT_SUCCESS = 'GET_COLONY_CLIENT_SUCCESS'

export const GET_COLONY_CLIENT_BY_ADDRESS = 'GET_COLONY_CLIENT_BY_ADDRESS'
export const GET_COLONY_CLIENT_BY_ADDRESS_ERROR = 'GET_COLONY_CLIENT_BY_ADDRESS_ERROR'
export const GET_COLONY_CLIENT_BY_ADDRESS_SUCCESS = 'GET_COLONY_CLIENT_BY_ADDRESS_SUCCESS'

export const GET_META_COLONY_CLIENT = 'GET_META_COLONY_CLIENT'
export const GET_META_COLONY_CLIENT_ERROR = 'GET_META_COLONY_CLIENT_ERROR'
export const GET_META_COLONY_CLIENT_SUCCESS = 'GET_META_COLONY_CLIENT_SUCCESS'

export const SET_STATE_COLONY_ADDRESS = 'SET_STATE_COLONY_ADDRESS'
export const SET_STATE_COLONY_CLIENT = 'SET_STATE_COLONY_CLIENT'
export const SET_STATE_META_COLONY_CLIENT = 'SET_STATE_META_COLONY_CLIENT'

// domainActions

export const GET_DOMAINS = 'GET_DOMAINS'
export const GET_DOMAINS_ERROR = 'GET_DOMAINS_ERROR'
export const GET_DOMAINS_SUCCESS = 'GET_DOMAINS_SUCCESS'

export const SET_STATE_DOMAINS = 'SET_STATE_DOMAINS'

// networkActions

export const GET_NETWORK_CLIENT = 'GET_NETWORK_CLIENT'
export const GET_NETWORK_CLIENT_ERROR = 'GET_NETWORK_CLIENT_ERROR'
export const GET_NETWORK_CLIENT_SUCCESS = 'GET_NETWORK_CLIENT_SUCCESS'

export const SET_STATE_NETWORK_CLIENT = 'SET_STATE_NETWORK_CLIENT'

// taskActions

export const CREATE_TASK = 'CREATE_TASK'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'

export const GET_TASK = 'GET_TASK'
export const GET_TASK_ERROR = 'GET_TASK_ERROR'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'

export const GET_TASKS = 'GET_TASKS'
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'

export const SET_STATE_TASK = 'SET_STATE_TASK'
export const SET_STATE_TASKS = 'SET_STATE_TASKS'

// tokenActions

export const CREATE_TOKEN = 'CREATE_TOKEN'
export const CREATE_TOKEN_ERROR = 'CREATE_TOKEN_ERROR'
export const CREATE_TOKEN_SUCCESS = 'CREATE_TOKEN_SUCCESS'

export const SET_STATE_TOKEN_ADDRESS = 'SET_STATE_TOKEN_ADDRESS'
