// colonyActions

export const CREATE_COLONY = 'CREATE_COLONY'
export const CREATE_COLONY_ERROR = 'CREATE_COLONY_ERROR'
export const CREATE_COLONY_SUCCESS = 'CREATE_COLONY_SUCCESS'

export const GET_COLONY_CLIENT = 'GET_COLONY_CLIENT'
export const GET_COLONY_CLIENT_ERROR = 'GET_COLONY_CLIENT_ERROR'
export const GET_COLONY_CLIENT_SUCCESS = 'GET_COLONY_CLIENT_SUCCESS'

export const GET_COLONY_CLIENT_BY_ADDRESS = 'GET_COLONY_CLIENT_BY_ADDRESS'
export const GET_COLONY_CLIENT_BY_ADDRESS_ERROR = 'GET_COLONY_CLIENT_BY_ADDRESS_ERROR'
export const GET_COLONY_CLIENT_BY_ADDRESS_SUCCESS = 'GET_COLONY_CLIENT_BY_ADDRESS_SUCCESS'

export const GET_META_COLONY_CLIENT = 'GET_META_COLONY_CLIENT'
export const GET_META_COLONY_CLIENT_ERROR = 'GET_META_COLONY_CLIENT_ERROR'
export const GET_META_COLONY_CLIENT_SUCCESS = 'GET_META_COLONY_CLIENT_SUCCESS'

export const SET_STATE_COLONY_CLIENT = 'SET_STATE_COLONY_CLIENT'
export const SET_STATE_META_COLONY_CLIENT = 'SET_STATE_META_COLONY_CLIENT'

// domainActions

export const GET_DOMAINS = 'GET_DOMAINS'
export const GET_DOMAINS_ERROR = 'GET_DOMAINS_ERROR'
export const GET_DOMAINS_SUCCESS = 'GET_DOMAINS_SUCCESS'

export const SET_STATE_DOMAINS = 'SET_STATE_DOMAINS'

// networkActions

export const GET_NETWORK_CLIENT = 'GET_NETWORK_CLIENT'
export const GET_NETWORK_CLIENT_ERROR = 'GET_NETWORK_CLIENT_ERROR'
export const GET_NETWORK_CLIENT_SUCCESS = 'GET_NETWORK_CLIENT_SUCCESS'

export const SET_STATE_NETWORK_CLIENT = 'SET_STATE_NETWORK_CLIENT'

// taskActions

export const CANCEL_TASK = 'CANCEL_TASK'
export const CANCEL_TASK_ERROR = 'CANCEL_TASK_ERROR'
export const CANCEL_TASK_SUCCESS = 'CANCEL_TASK_SUCCESS'

export const CLAIM_TASK = 'CLAIM_TASK'
export const CLAIM_TASK_ERROR = 'CLAIM_TASK_ERROR'
export const CLAIM_TASK_SUCCESS = 'CLAIM_TASK_SUCCESS'

export const CREATE_TASK = 'CREATE_TASK'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'

export const FINALIZE_TASK = 'FINALIZE_TASK'
export const FINALIZE_TASK_ERROR = 'FINALIZE_TASK_ERROR'
export const FINALIZE_TASK_SUCCESS = 'FINALIZE_TASK_SUCCESS'

export const GET_TASK = 'GET_TASK'
export const GET_TASK_ERROR = 'GET_TASK_ERROR'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'

export const GET_TASKS = 'GET_TASKS'
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'

export const MINT_TOKENS = 'MINT_TOKENS'
export const MINT_TOKENS_ERROR = 'MINT_TOKENS_ERROR'
export const MINT_TOKENS_SUCCESS = 'MINT_TOKENS_SUCCESS'

export const SET_STATE_TASK = 'SET_STATE_TASK'
export const SET_STATE_TASKS = 'SET_STATE_TASKS'

export const SET_TASK_DUE_DATE = 'SET_TASK_DUE_DATE'
export const SET_TASK_DUE_DATE_ERROR = 'SET_TASK_DUE_DATE_ERROR'
export const SET_TASK_DUE_DATE_SUCCESS = 'SET_TASK_DUE_DATE_SUCCESS'

export const SET_TASK_ROLE = 'SET_TASK_ROLE'
export const SET_TASK_ROLE_ERROR = 'SET_TASK_ROLE_ERROR'
export const SET_TASK_ROLE_SUCCESS = 'SET_TASK_ROLE_SUCCESS'

export const SIGN_TASK_DUE_DATE = 'SIGN_TASK_DUE_DATE'
export const SIGN_TASK_DUE_DATE_ERROR = 'SIGN_TASK_DUE_DATE_ERROR'
export const SIGN_TASK_DUE_DATE_SUCCESS = 'SIGN_TASK_DUE_DATE_SUCCESS'

// tokenActions

export const CREATE_TOKEN = 'CREATE_TOKEN'
export const CREATE_TOKEN_ERROR = 'CREATE_TOKEN_ERROR'
export const CREATE_TOKEN_SUCCESS = 'CREATE_TOKEN_SUCCESS'

export const GET_TOKEN = 'GET_TOKEN'
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'

export const SET_STATE_TOKEN = 'SET_STATE_TOKEN'
export const SET_STATE_TOKEN_ADDRESS = 'SET_STATE_TOKEN_ADDRESS'
